---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: broker-demo
  namespace: demo
  annotations:
    flux.weave.works/automated: 'true'
# This should only pick up images with X.Y.Z release tag and sort them properly as per version increases
    flux.weave.works/tag.chart-image: 'semver:*'
spec:
  releaseName: broker-demo
  chart:
    git: git@github.ibm.com:fd4b-demo/demoKubernetes.git
    ref: master
    path: broker-demo
  values:
    appReplicaCount: 1
    DOCKER_REGISTRY_SECRET: regcred
    #redis
    REDIS_HOST: d8b3a646-6c7f-4dfe-b448-cc2634d06d64.3c7f6c12a66c4324800651be37a77ceb.databases.appdomain.cloud
    REDIS_PORT: 32305
    REDIS_DB: 0
    REDIS_SSL: true
    BROKER_TYPE: demo
    #psql
    PSQL_HOST: 87a3108e-5cdd-4bb5-89a5-1bf6b32df4b9.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud
    PSQL_PORT: 31414
    PSQL_DB: ibmclouddb
    PSQL_USER: ibm_cloud_7d69f812_27ec_4b9b_bd49_8687fccb0e73

    #image
    image: de.icr.io/fd4b-demo/broker-demo
    tag: 0.0.3
    #Resource
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
