# Copyright 2019 IBM Corporation All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: logdna
  namespace: demo
  annotations:
    flux.weave.works/automated: 'true'
# This should only pick up images with X.Y.Z release tag and sort them properly as per version increases
    flux.weave.works/tag.chart-image: 'glob:*'
spec:
  releaseName: logdna
  chart:
    git: git@github.com:marchmallow/ibm-cloud-dublin-meetup.git
    ref: master
    path: demoCharts/logdna
  values:
    image: logdna/logdna-agent:1.5.6
    TAGS: best-meetup
