# Copyright 2019 IBM Corporation All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: {{ template "demo-listener.fullname" . }}
  labels:
    app: {{ .Values.appName }}
    chart: {{ template "demo-listener.fullname" . }}
spec:
  replicas: {{ .Values.appReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      chart: {{ template "demo-listener.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge  }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        chart: {{ template "demo-listener.fullname" . }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.DOCKER_REGISTRY_SECRET }}
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        resources:
          limits:
            memory: "{{ .Values.limits.memory }}"
          requests:
            memory: "{{ .Values.requests.memory }}"
        securityContext:
          privileged: true
        ports:
        - name: http-app
          containerPort: {{ .Values.appPort | default 8080 }}
        env:

        - name: PSQL_HOST
          value: {{ .Values.PSQL_HOST }}
        - name: PSQL_PORT
          value: {{ .Values.PSQL_PORT | quote }}
        - name: PSQL_DB
          value: {{ .Values.PSQL_DB  }}
        - name: PSQL_USER
          value: {{ .Values.PSQL_USER  }}
        - name: PSQL_PASSWORD
#          value: {{ .Values.PSQL_PASSWORD | quote }}
          valueFrom:
            secretKeyRef:
              name: psql-password
              key: PSQL_PASSWORD


        - name: LISTENER_TYPE
          value: {{ .Values.LISTENER_TYPE }}
        - name: REDIS_HOST
          value: {{ .Values.REDIS_HOST }}
        - name: REDIS_PORT
          value: {{ .Values.REDIS_PORT | quote }}
        - name: REDIS_DB
          value: {{ .Values.REDIS_DB | quote }}
        - name: REDIS_SSL
          value: {{ .Values.REDIS_SSL | quote }}
        - name: REDIS_PASSWORD
#          value: {{ .Values.REDIS_PASSWORD }}
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: REDIS_PASSWORD
